
CREATE ROLE :databaseAppRole WITH
 NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE :databaseAppUser WITH
	LOGIN PASSWORD :databaseAppUserPassword
	NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION IN ROLE :databaseAppRole;

GRANT ALL ON DATABASE :databaseName TO :databaseAdmin;
GRANT CONNECT, TEMPORARY ON DATABASE :databaseName TO :databaseAppRole;
REVOKE ALL ON DATABASE :databaseName FROM public;

CREATE SCHEMA :databaseSchema AUTHORIZATION :databaseAdmin;

GRANT USAGE ON SCHEMA :databaseSchema TO :databaseAppRole;

ALTER DEFAULT PRIVILEGES IN SCHEMA :databaseSchema
 GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
 TO :databaseAppRole;

ALTER DEFAULT PRIVILEGES IN SCHEMA :databaseSchema
 GRANT SELECT, USAGE ON SEQUENCES
 TO :databaseAppRole;
 
ALTER DEFAULT PRIVILEGES IN SCHEMA :databaseSchema
 GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
 TO :databaseAppUser;

ALTER DEFAULT PRIVILEGES IN SCHEMA :databaseSchema
 GRANT SELECT, USAGE ON SEQUENCES
 TO :databaseAppUser;

ALTER USER :databaseAppUser PASSWORD :databaseAppUserPassword;
 

---CREATE SCHEMA :liquibaseSchema AUTHORIZATION :databaseAdmin;
